---
ID: "4e6980a6-b775-42d3-8afe-e727d9d9e4d6"
Parent: "b41faba6-b4c5-4101-9f4a-db2e5c159c7f"
Template: "b41faba6-b4c5-4101-9f4a-db2e5c159c7f"
Path: "/sitecore/templates/Feature/swag-store/Data source Template/Global components/Header/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231028T064554Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d41bb007-62b9-41d3-8468-58bd83f66094"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231028T064554Z
