---
ID: "33f83d00-e3da-45d3-a161-094bc7787622"
Parent: "0ff8e4bb-c925-4932-9a03-0c90cbadc25d"
Template: "0ff8e4bb-c925-4932-9a03-0c90cbadc25d"
Path: "/sitecore/templates/Feature/swag-store/Data source Template/Banner/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231028T055131Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ac6176ac-13ee-4c7d-b57d-28072271d41c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231028T055159Z
    - ID: "e43a95dd-553f-4a11-a738-27b72c3f4f13"
      Hint: title
      Value: $name
