---
ID: "5ee12bf9-6c75-4a23-ac91-d57e33e8d994"
Parent: "588b44df-29c8-491e-9e15-70677ff4f825"
Template: "588b44df-29c8-491e-9e15-70677ff4f825"
Path: "/sitecore/templates/Feature/swag-store/Data source Template/Tab Component/Tab/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231029T064426Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "54da3833-f2a3-4cca-a4ab-20194abf1a2a"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2e7b66af-6fc2-4496-9d94-4b4efb8fd535"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231029T064446Z
