
/**
 * <auto-generated>
 *     This code was generated by a tool.
 *
 *     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 * </auto-generated>
 */ 

// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { Sitecore } from "./_.Sitecore.Override"
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { ComponentRendering, RouteData, Field, ImageField, FileField, LinkField } from '@sitecore-jss/sitecore-jss-nextjs';
// @ts-ignore Prevent noUnusedLocals from triggering an error, we import all core field types to minimize changing to code generation.
import { DefaultComponentProps } from '@/lib/component-props';


export namespace Sample.HZTLSWAG.feature-templates.Sitecore.templates.swagstore.DataSourceTemplate.Fields {
    export type Banner = { 
        fields?: { 
            /**
            * Represents the ctaButton field (32d83320-1d57-4294-921b-40bea7ec0e91).
            */
            ctaButton: LinkField;

            /**
            * Represents the description field (cb4246e3-0fe2-4d35-972b-1a912fcfcb32).
            */
            description: Field<string>;

            /**
            * Represents the image field (5ec05182-e32c-4c89-bed6-3dc5e4752e22).
            */
            image: ImageField;

            /**
            * Represents the title field (e43a95dd-553f-4a11-a738-27b72c3f4f13).
            */
            title: Field<string>;
 
        }
 }; 
}

export namespace Sample.HZTLSWAG.feature-templates.Sitecore.templates.swagstore.DataSourceTemplate.Fields {
    export type ContentBlock = { 
        fields?: { 
            /**
            * Represents the cta1 field (2c9de173-7948-4d54-a6d5-f80c7c73cbf8).
            */
            cta1: LinkField;

            /**
            * Represents the description field (58003d1f-7acb-4ee5-93cf-2bdfcb418024).
            */
            description: Field<string>;

            /**
            * Represents the headingText field (2d7b4330-1fc1-49c8-bbd2-515964d8a2ca).
            */
            headingText: Field<string>;

            /**
            * Represents the image field (b91ee507-3b71-481b-a5e7-f8dfe50626a7).
            */
            image: ImageField;

            /**
            * Represents the imageOnLeft field (aa084b7d-72cb-455b-b1ae-ade4ca25dcca).
            */
            imageOnLeft: Field<boolean>;
 
        }
 }; 
}

export namespace Sample.HZTLSWAG.feature-templates.Sitecore.templates.swagstore.DataSourceTemplate.Fields {
    export type Header = { 
        fields?: {  
        }
 }; 
}

export namespace Sample.HZTLSWAG.feature-templates.Sitecore.templates.swagstore.PageTemplate.Fields {
    export type HomePage = 
            Sample.HZTLSWAG.feature-templates.Sitecore.templates.swagstore.DataSourceTemplate.Fields.ContentBlock & { 
        fields?: {  
        }
 }; 
}


